FROM maven:3.8.6-openjdk-11-slim
MAINTAINER narendra.singh@geminisolutions.com
COPY ./target/ReportManager*.jar /home/
WORKDIR /home/
EXPOSE 8004
RUN mkdir /var/log/jewel-reportmanager
ENTRYPOINT ["java","-jar","ReportManager-1.0.0.jar"]